### ISSUE TITLE
Deployment on Sepolia

### ISSUE THREAD

**Issue by brunomenezes** [cartesi/staking-pool#32]
## 📄 Context
This is part of effort from Explorer PR: https://github.com/cartesi/explorer/pull/146 to have all PoS related contract deployed on Sepolia. Therefore allowing explorer to support Sepolia while deprecating the Goerli testnet.

## 📈 Subtasks

- [ ] Upgrade the PoS lib to latest version (depends on: https://github.com/cartesi/pos-dlib/issues/4)
- [ ] Deploy contracts to the Sepolia network
- [ ] Publish a new version of `@cartesi/staking-pool` on [npmjs](https://www.npmjs.com/package/@cartesi/staking-pool)

**Comment by brunomenezes** [comment]
@tuler, it has a dependency on another issue as stated, but who could give a hand here? Maybe same person so it can be done in one `blazingly` fast blow?
